### ISSUE TITLE
ae tham khảo cách code theo đúng format giúp mọi người dễ đọc

### ISSUE THREAD

**Issue by monthui0002** [monthui0002/AStarAlgorithm#1]
- một class nên chứa **<=5 function.**
- mỗi function nên **nhỏ hơn 25 dòng**.
- **khai báo rõ** biến nào là **toàn cục**, biến nào là **cục bộ** trong mỗi class.
- triển khai A* trong 1 **package riêng** và **chia thành nhiều file** nếu file gốc quá dài.
- đối với A* : **input** là 1 ma trận cỡ **m*n** (tôi đang làm là 30x30) với các ô có thể đi qua là 0, tương tự với không đi qua được, ô bắt đầu và ô kết thúc. **output** là ma trận input với những ô mà A* đã duyệt 1 giá trị riêng, ô mà A* chọn làm ô đi qua để được đường đi ngắn nhất 1 giá trị riêng nữa. 
- **Thứ 5** ae nhớ send nude code hoặc push luôn lên đây vào **package khác** nhé. có thể push cả bản báo cáo sơ bộ về A* lên 1 dir riêng nữa. nhớ push lên thì nhắn vào nhóm nhé.
Thân.

**Comment by nvhuy1509** [comment]
Tôi ít dùng cái này nên có gì send nude code cho ae ở chỗ khác nhé :(
